### ISSUE TITLE
PMM2: doc issue on page  'MySQL and variants' (setting-up/client/mysql.html) can't use "slow query log"

### ISSUE THREAD

**Issue by maxkondr** [percona/pmm-doc#483]
Hi,

In case the PMM Client is deployed via docker container (https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/client/index.html#docker) or docker-compose (https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/client/index.html#docker-compose) it can't use MySQL's slow query log as described at 
https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/client/mysql.html#slow-query-log as soon as '/var/lib/mysql' directory is not mounted into docker container from host machine.

And it can't rotate 'slowquery.log' file due to the same reason.

Please adjust the instructions accordingly.

**Comment by PaulJacobs-percona** [comment]
Hi @maxkondr thanks for spotting that. Do you know what the workaround is? I'm guessing the docker[-compose] command needs an additional volume mount?
@shoffman-percona @BupycHuk Any idea?

**Comment by maxkondr** [comment]
I have the following docker-compose file:

```
version: '3'
services:
  mysql-8:
    image: percona/percona-server:8.0.22
    hostname: mysql-8-yakut-mac
    container_name: mysql-8
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - pmm
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf.d/yakut.cnf:ro
      - ./init-db:/docker-entrypoint-initdb.d
volumes:
  mysql-data:

networks:
  pmm:
    external:
      name: pmm2

```

and yes, I mounted MySQL data dir into agent container.
